# Generated by Django 5.0.4 on 2026-06-24 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.project'),
        ),
        migrations.AddField(
            model_name='application',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectrole'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['project', 'status'], name='application_project_f37dca_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'status'], name='application_applica_b6966f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('project', 'applicant', 'role')},
        ),
    ]
